  // ====================================================
  // BATCH: Convert block and array ids from serial to varchar
  // Payload v3 generates String UUIDs for block/array IDs,
  // but they were originally created as serial integers.
  // ====================================================
  `ALTER TABLE "_pages_v_blocks_magazine_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_magazine_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_magazine_block_magazine_pages" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_magazine_block_magazine_pages" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_schedule_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_schedule_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_schedule_block_schedule_groups" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_schedule_block_schedule_groups" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_schedule_block_schedule_groups_time_slots" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_schedule_block_schedule_groups_time_slots" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_schedule_block_highlight_box_content" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_schedule_block_highlight_box_content" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_categories_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_categories_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_recent_articles_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_recent_articles_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_tiktok_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_tiktok_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_facebook_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_facebook_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_banner_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_banner_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_custom_html_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_custom_html_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "main_menu_menu_items" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "main_menu_menu_items" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "main_menu_menu_items_sub_items" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "main_menu_menu_items_sub_items" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_news_category_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_news_category_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_banner_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_banner_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_multi_banner_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_multi_banner_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_multi_banner_section_banners" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_multi_banner_section_banners" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_video_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_video_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_tiktok_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_tiktok_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_stats_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_stats_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_stats_section_stats" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_stats_section_stats" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_quick_links_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_quick_links_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_quick_links_section_links" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_quick_links_section_links" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "settings_blocks_rich_text_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "settings_blocks_rich_text_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_rich_text_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_rich_text_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_section_title_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_section_title_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_card_grid_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_card_grid_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_card_grid_block_cards" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_card_grid_block_cards" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_steps_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_steps_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_steps_block_steps" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_steps_block_steps" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_faq_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_faq_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_faq_block_faqs" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_faq_block_faqs" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_divider_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_divider_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_cta_banner_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_cta_banner_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_embed_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_embed_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_table_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_table_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_table_block_headers" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_table_block_headers" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_table_block_rows" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_table_block_rows" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "pages_blocks_table_block_rows_cells" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "pages_blocks_table_block_rows_cells" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_menu_menu_items" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_menu_menu_items" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_menu_menu_items_sub_items" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_menu_menu_items_sub_items" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_category_news" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_category_news" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_footer_quick_links" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_footer_quick_links" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_footer_social_links" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_footer_social_links" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_rich_text_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_rich_text_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_section_title_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_section_title_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_callout_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_callout_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_columns_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_columns_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_divider_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_divider_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_card_grid_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_card_grid_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_card_grid_block_cards" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_card_grid_block_cards" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_card_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_card_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_steps_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_steps_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_steps_block_steps" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_steps_block_steps" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_faq_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_faq_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_faq_block_faqs" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_faq_block_faqs" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_button_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_button_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_cta_banner_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_cta_banner_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_video_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_video_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_tiktok_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_tiktok_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_gallery_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_gallery_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_gallery_block_images" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_gallery_block_images" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_pdf_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_pdf_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_embed_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_embed_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_table_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_table_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_table_block_headers" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_table_block_headers" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_table_block_rows" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_table_block_rows" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_table_block_rows_cells" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_table_block_rows_cells" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_related_articles_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_related_articles_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_category_news" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_category_news" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_quote_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_quote_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_audio_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_audio_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_file_downloads_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_file_downloads_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_file_downloads_block_files" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_file_downloads_block_files" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_slider_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_slider_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_slider_block_images" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_slider_block_images" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_infographic_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_infographic_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_zalo_widget_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_zalo_widget_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_livestream_block" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_livestream_block" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "_pages_v_blocks_hero_banner" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "_pages_v_blocks_hero_banner" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_categories_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_categories_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_recent_articles_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_recent_articles_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_tiktok_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_tiktok_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_facebook_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_facebook_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_banner_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_banner_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_custom_html_widget" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_custom_html_widget" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_news_category_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_news_category_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_banner_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_banner_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_multi_banner_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_multi_banner_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_video_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_video_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_tiktok_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_tiktok_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_stats_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_stats_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_quick_links_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_quick_links_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_rich_text_section" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_rich_text_section" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_category_news" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_category_news" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_stats_section_stats" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_stats_section_stats" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_blocks_quick_links_section_links" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_blocks_quick_links_section_links" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_menu_menu_items" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_menu_menu_items" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_menu_menu_items_sub_items" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_menu_menu_items_sub_items" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_footer_quick_links" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_footer_quick_links" ALTER COLUMN "id" TYPE varchar USING id::varchar`,
  `ALTER TABLE "site_settings_footer_social_links" ALTER COLUMN "id" DROP DEFAULT`,
  `ALTER TABLE "site_settings_footer_social_links" ALTER COLUMN "id" TYPE varchar USING id::varchar`,